### ISSUE TITLE
why "react-router": "nicolashery/react-router#2e375e94033e1cab5ed5b922395a79e368bb1929" ?

### ISSUE THREAD

**Issue by ngthorg** [nicolashery/example-isomorphic-one#3]
why "react-router": "nicolashery/react-router#2e375e94033e1cab5ed5b922395a79e368bb1929" in package.json?

you use "react-router": "^0.13.2"
=> error 
TypeError: Cannot read property 'getActionContext' of undefined
    at Route.module.exports.statics.willTransitionTo [as onEnter](/home/unix/Templates/example-isomorphic-test/src/utils/AuthMixin.js:7:9)

**Comment by nicolashery** [comment]
Currently React Router does not support `transitionContext`, so I need to use my own fork to be able to do this:

``` javascript
var router = Router.create({
    routes: routes,
    location: Router.HistoryLocation,
    transitionContext: context
  });
```

This allows me to fetch the Fluxible context during a transition:

``` javascript
    willTransitionTo: function(transition) {
      var isAuthenticated = transition.context
        .getActionContext().getStore(AuthStore).isAuthenticated();

      if (!isAuthenticated) {
        transition.redirect('/signin');
      }
    }
```
